import type { Student, SemesterRecord, CourseEnrollment } from '@/types/student';

const mockCourses: CourseEnrollment[] = [
  {
    id: '4011-CS101',
    code: 'CS101',
    name: 'مبانی برنامه‌سازی',
    units: 3,
    grade: 18,
    status: 'passed',
    term_id: '4011',
    course_code: 'CS101',
    course_name: 'مبانی برنامه‌سازی',
    course_units: 3,
    course_type: 'اصلی',
    grade_state: 'نهایی',
  },
];

const mockSemesters: SemesterRecord[] = [
  {
    id: '4011',
    term_code: '4011',
    term_name: 'نیمسال اول 1401-1402',
    term_gpa: 18,
    units_passed: 3,
    units_total: 3,
    courses: mockCourses,
    semester_id: 4011,
    semester_description: 'نیمسال اول 1401-1402',
    semester_gpa: 18,
    units_taken: 3,
    units_failed: 0,
    units_dropped: 0,
    cumulative_gpa: 18,
    cumulative_units_passed: 3,
    semester_status: null,
    semester_type: null,
    probation_status: null,
  },
];

export const mockStudent: Student = {
  student_id: '99999999',
  name: 'دانشجوی نمونه',
  father_name: 'نمونه',
  faculty: 'فنی و مهندسی',
  department: 'مهندسی کامپیوتر',
  major: 'مهندسی کامپیوتر',
  degree_level: 'کارشناسی',
  study_type: 'روزانه',
  enrollment_status: 'در حال تحصیل',
  registration_permission: true,
  overall_gpa: 18,
  total_units_passed: 3,
  total_probation: 0,
  consecutive_probation: 0,
  special_probation: 0,
  semesters: mockSemesters,
  updated_at: new Date().toISOString(),
  image_b64: null,
  total_gpa: 18,
  total_units: 140,
  best_term_gpa: 18,
};