import type { Student } from '@/types/student';

/**
 * Comprehensive mock student representing a 5th-semester student.
 * This mirrors the richness of the Windows app data model.
 */
export const mockStudent: Student = {
  student_id: '400123456',
  name: 'علی علوی',
  father_name: 'حسین علوی',
  faculty: 'فنی و مهندسی',
  department: 'گروه مهندسی کامپیوتر',
  major: 'مهندسی کامپیوتر',
  degree_level: 'کارشناسی',
  study_type: 'روزانه',
  enrollment_status: 'در حال تحصیل',
  registration_permission: true,
  overall_gpa: 16.98,
  total_units_passed: 78,
  total_probation: 0,
  consecutive_probation: 0,
  special_probation: 0,
  // Web-UI convenience fields
  total_gpa: 16.98,
  total_units: 140,
  best_term_gpa: 18.75,
  // 1x1 transparent PNG (placeholder)
  image_b64:
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=',
  updated_at: '2024-09-01T12:00:00Z',
  semesters: [
    {
      id: '4001',
      term_code: '4001',
      term_name: 'نیمسال اول 1400-1401',
      term_gpa: 15.4,
      units_passed: 16,
      units_total: 16,
      // Raw fields roughly mirroring the legacy SemesterRecord
      semester_id: 4001,
      semester_description: 'نیمسال اول 1400-1401',
      semester_gpa: 15.4,
      units_taken: 16,
      units_failed: 0,
      units_dropped: 0,
      cumulative_gpa: 15.4,
      cumulative_units_passed: 16,
      semester_status: 'عادی',
      semester_type: 'تحصیلی',
      probation_status: null,
      courses: [
        {
          id: '4001-math1',
          code: '400101',
          name: 'ریاضی عمومی 1',
          units: 3,
          grade: 15.0,
          status: 'passed',
          term_id: '4001',
          course_code: '400101',
          course_name: 'ریاضی عمومی 1',
          course_units: 3,
          course_type: 'نظری',
          grade_state: 'نهایی',
        },
        {
          id: '4001-phys1',
          code: '400102',
          name: 'فیزیک 1',
          units: 3,
          grade: 14.5,
          status: 'passed',
          term_id: '4001',
          course_code: '400102',
          course_name: 'فیزیک 1',
          course_units: 3,
          course_type: 'نظری',
          grade_state: 'نهایی',
        },
        {
          id: '4001-intro-cs',
          code: '400103',
          name: 'مبانی کامپیوتر و برنامه‌سازی',
          units: 3,
          grade: 16.0,
          status: 'passed',
          term_id: '4001',
          course_code: '400103',
          course_name: 'مبانی کامپیوتر و برنامه‌سازی',
          course_units: 3,
          course_type: 'نظری',
          grade_state: 'نهایی',
        },
        {
          id: '4001-fa',
          code: '400104',
          name: 'فارسی عمومی',
          units: 2,
          grade: 15.75,
          status: 'passed',
          term_id: '4001',
          course_code: '400104',
          course_name: 'فارسی عمومی',
          course_units: 2,
          course_type: 'عمومی',
          grade_state: 'نهایی',
        },
        {
          id: '4001-pe',
          code: '400105',
          name: 'تربیت بدنی 1',
          units: 1,
          grade: 17.0,
          status: 'passed',
          term_id: '4001',
          course_code: '400105',
          course_name: 'تربیت بدنی 1',
          course_units: 1,
          course_type: 'عملی',
          grade_state: 'نهایی',
        },
      ],
    },
    {
      id: '4002',
      term_code: '4002',
      term_name: 'نیمسال دوم 1400-1401',
      term_gpa: 16.2,
      units_passed: 17,
      units_total: 18,
      semester_id: 4002,
      semester_description: 'نیمسال دوم 1400-1401',
      semester_gpa: 16.2,
      units_taken: 18,
      units_failed: 1,
      units_dropped: 0,
      cumulative_gpa: 16.0,
      cumulative_units_passed: 33,
      semester_status: 'عادی',
      semester_type: 'تحصیلی',
      probation_status: null,
      courses: [
        {
          id: '4002-math2',
          code: '400201',
          name: 'ریاضی عمومی 2',
          units: 3,
          grade: 16.0,
          status: 'passed',
          term_id: '4002',
          course_code: '400201',
          course_name: 'ریاضی عمومی 2',
          course_units: 3,
          course_type: 'نظری',
          grade_state: 'نهایی',
        },
        {
          id: '4002-phys2',
          code: '400202',
          name: 'فیزیک 2',
          units: 3,
          grade: 15.5,
          status: 'passed',
          term_id: '4002',
          course_code: '400202',
          course_name: 'فیزیک 2',
          course_units: 3,
          course_type: 'نظری',
          grade_state: 'نهایی',
        },
        {
          id: '4002-discrete',
          code: '400203',
          name: 'ریاضیات گسسته',
          units: 3,
          grade: 17.0,
          status: 'passed',
          term_id: '4002',
          course_code: '400203',
          course_name: 'ریاضیات گسسته',
          course_units: 3,
          course_type: 'نظری',
          grade_state: 'نهایی',
        },
        {
          id: '4002-prog1',
          code: '400204',
          name: 'برنامه‌نویسی پیشرفته',
          units: 3,
          grade: 16.5,
          status: 'passed',
          term_id: '4002',
          course_code: '400204',
          course_name: 'برنامه‌نویسی پیشرفته',
          course_units: 3,
          course_type: 'نظری-عملی',
          grade_state: 'نهایی',
        },
        {
          id: '4002-eng',
          code: '400205',
          name: 'زبان انگلیسی عمومی',
          units: 2,
          grade: 16.25,
          status: 'passed',
          term_id: '4002',
          course_code: '400205',
          course_name: 'زبان انگلیسی عمومی',
          course_units: 2,
          course_type: 'عمومی',
          grade_state: 'نهایی',
        },
        {
          id: '4002-pe2',
          code: '400206',
          name: 'تربیت بدنی 2',
          units: 1,
          grade: 17.5,
          status: 'passed',
          term_id: '4002',
          course_code: '400206',
          course_name: 'تربیت بدنی 2',
          course_units: 1,
          course_type: 'عملی',
          grade_state: 'نهایی',
        },
      ],
    },
    {
      id: '4011',
      term_code: '4011',
      term_name: 'نیمسال اول 1401-1402',
      term_gpa: 17.3,
      units_passed: 16,
      units_total: 17,
      semester_id: 4011,
      semester_description: 'نیمسال اول 1401-1402',
      semester_gpa: 17.3,
      units_taken: 17,
      units_failed: 1,
      units_dropped: 0,
      cumulative_gpa: 16.5,
      cumulative_units_passed: 50,
      semester_status: 'عادی',
      semester_type: 'تحصیلی',
      probation_status: null,
      courses: [
        {
          id: '4011-ds',
          code: '401101',
          name: 'ساختمان داده‌ها',
          units: 3,
          grade: 17.75,
          status: 'passed',
          term_id: '4011',
          course_code: '401101',
          course_name: 'ساختمان داده‌ها',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4011-alg',
          code: '401102',
          name: 'طراحی الگوریتم‌ها',
          units: 3,
          grade: 17.25,
          status: 'passed',
          term_id: '4011',
          course_code: '401102',
          course_name: 'طراحی الگوریتم‌ها',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4011-arch',
          code: '401103',
          name: 'معماری کامپیوتر',
          units: 3,
          grade: 16.5,
          status: 'passed',
          term_id: '4011',
          course_code: '401103',
          course_name: 'معماری کامپیوتر',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4011-logic',
          code: '401104',
          name: 'مدارهای منطقی',
          units: 3,
          grade: 17.0,
          status: 'passed',
          term_id: '4011',
          course_code: '401104',
          course_name: 'مدارهای منطقی',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4011-islamic',
          code: '401105',
          name: 'اندیشه اسلامی 1',
          units: 2,
          grade: 16.0,
          status: 'passed',
          term_id: '4011',
          course_code: '401105',
          course_name: 'اندیشه اسلامی 1',
          course_units: 2,
          course_type: 'عمومی',
          grade_state: 'نهایی',
        },
        {
          id: '4011-persian',
          code: '401106',
          name: 'زبان فارسی تخصصی',
          units: 3,
          grade: 18.0,
          status: 'passed',
          term_id: '4011',
          course_code: '401106',
          course_name: 'زبان فارسی تخصصی',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
      ],
    },
    {
      id: '4012',
      term_code: '4012',
      term_name: 'نیمسال دوم 1401-1402',
      term_gpa: 18.75,
      units_passed: 15,
      units_total: 15,
      semester_id: 4012,
      semester_description: 'نیمسال دوم 1401-1402',
      semester_gpa: 18.75,
      units_taken: 15,
      units_failed: 0,
      units_dropped: 0,
      cumulative_gpa: 17.2,
      cumulative_units_passed: 65,
      semester_status: 'عالی',
      semester_type: 'تحصیلی',
      probation_status: null,
      courses: [
        {
          id: '4012-os',
          code: '401201',
          name: 'سیستم‌عامل',
          units: 3,
          grade: 18.5,
          status: 'passed',
          term_id: '4012',
          course_code: '401201',
          course_name: 'سیستم‌عامل',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4012-db',
          code: '401202',
          name: 'پایگاه داده‌ها',
          units: 3,
          grade: 18.75,
          status: 'passed',
          term_id: '4012',
          course_code: '401202',
          course_name: 'پایگاه داده‌ها',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4012-net',
          code: '401203',
          name: 'شبکه‌های کامپیوتری',
          units: 3,
          grade: 18.25,
          status: 'passed',
          term_id: '4012',
          course_code: '401203',
          course_name: 'شبکه‌های کامپیوتری',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4012-se',
          code: '401204',
          name: 'مهندسی نرم‌افزار',
          units: 3,
          grade: 19.0,
          status: 'passed',
          term_id: '4012',
          course_code: '401204',
          course_name: 'مهندسی نرم‌افزار',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4012-islamic2',
          code: '401205',
          name: 'اندیشه اسلامی 2',
          units: 3,
          grade: 18.25,
          status: 'passed',
          term_id: '4012',
          course_code: '401205',
          course_name: 'اندیشه اسلامی 2',
          course_units: 3,
          course_type: 'عمومی',
          grade_state: 'نهایی',
        },
      ],
    },
    {
      id: '4021',
      term_code: '4021',
      term_name: 'نیمسال اول 1402-1403',
      term_gpa: 17.85,
      units_passed: 14,
      units_total: 15,
      semester_id: 4021,
      semester_description: 'نیمسال اول 1402-1403',
      semester_gpa: 17.85,
      units_taken: 15,
      units_failed: 0,
      units_dropped: 0,
      cumulative_gpa: 17.5,
      cumulative_units_passed: 79,
      semester_status: 'عادی',
      semester_type: 'تحصیلی',
      probation_status: null,
      courses: [
        {
          id: '4021-ai',
          code: '402101',
          name: 'هوش مصنوعی',
          units: 3,
          grade: 18.0,
          status: 'passed',
          term_id: '4021',
          course_code: '402101',
          course_name: 'هوش مصنوعی',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4021-theory',
          code: '402102',
          name: 'نظریه زبان‌ها و ماشین‌ها',
          units: 3,
          grade: 17.5,
          status: 'passed',
          term_id: '4021',
          course_code: '402102',
          course_name: 'نظریه زبان‌ها و ماشین‌ها',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4021-compiler',
          code: '402103',
          name: 'مبانی ترجمه و زبان‌های برنامه‌سازی',
          units: 3,
          grade: 17.75,
          status: 'passed',
          term_id: '4021',
          course_code: '402103',
          course_name: 'مبانی ترجمه و زبان‌های برنامه‌سازی',
          course_units: 3,
          course_type: 'تخصصی',
          grade_state: 'نهایی',
        },
        {
          id: '4021-research',
          code: '402104',
          name: 'روش پژوهش و ارائه',
          units: 2,
          grade: 17.0,
          status: 'passed',
          term_id: '4021',
          course_code: '402104',
          course_name: 'روش پژوهش و ارائه',
          course_units: 2,
          course_type: 'عمومی',
          grade_state: 'نهایی',
        },
        {
          id: '4021-pe3',
          code: '402105',
          name: 'ورزش 3',
          units: 1,
          grade: 18.0,
          status: 'passed',
          term_id: '4021',
          course_code: '402105',
          course_name: 'ورزش 3',
          course_units: 1,
          course_type: 'عملی',
          grade_state: 'نهایی',
        },
      ],
    },
  ],
};