import type { Student } from '@/types/student';

/**
 * Comprehensive mock student representing a 5th-semester student.
 * This mirrors the richness of the Windows app data model.
 */
export const mockStudent: Student = {
  student_id: '400123456',
  name: 'علی علوی',
  major: 'مهندسی کامپیوتر',
  faculty: 'فنی و مهندسی',
  total_gpa: 16.98,
  total_units_passed: 78,
  total_units: 140,
  best_term_gpa: 18.75,
  // 1x1 transparent PNG (placeholder)
  image_b64:
    'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR4nGNgYAAAAAMAASsJTYQAAAAASUVORK5CYII=',
  semesters: [
    {
      id: '4001',
      term_code: '4001',
      term_name: 'نیمسال اول 1400-1401',
      term_gpa: 15.4,
      units_passed: 16,
      units_total: 16,
      courses: [
        {
          id: '4001-math1',
          code: '400101',
          name: 'ریاضی عمومی 1',
          units: 3,
          grade: 15.0,
          status: 'passed',
          term_id: '4001',
        },
        {
          id: '4001-phys1',
          code: '400102',
          name: 'فیزیک 1',
          units: 3,
          grade: 14.5,
          status: 'passed',
          term_id: '4001',
        },
        {
          id: '4001-intro-cs',
          code: '400103',
          name: 'مبانی کامپیوتر و برنامه‌سازی',
          units: 3,
          grade: 16.0,
          status: 'passed',
          term_id: '4001',
        },
        {
          id: '4001-fa',
          code: '400104',
          name: 'فارسی عمومی',
          units: 2,
          grade: 15.75,
          status: 'passed',
          term_id: '4001',
        },
        {
          id: '4001-pe',
          code: '400105',
          name: 'تربیت بدنی 1',
          units: 1,
          grade: 17.0,
          status: 'passed',
          term_id: '4001',
        },
      ],
    },
    {
      id: '4002',
      term_code: '4002',
      term_name: 'نیمسال دوم 1400-1401',
      term_gpa: 16.2,
      units_passed: 17,
      units_total: 18,
      courses: [
        {
          id: '4002-math2',
          code: '400201',
          name: 'ریاضی عمومی 2',
          units: 3,
          grade: 16.0,
          status: 'passed',
          term_id: '4002',
        },
        {
          id: '4002-phys2',
          code: '400202',
          name: 'فیزیک 2',
          units: 3,
          grade: 15.5,
          status: 'passed',
          term_id: '4002',
        },
        {
          id: '4002-discrete',
          code: '400203',
          name: 'ریاضیات گسسته',
          units: 3,
          grade: 17.0,
          status: 'passed',
          term_id: '4002',
        },
        {
          id: '4002-prog1',
          code: '400204',
          name: 'برنامه‌نویسی پیشرفته',
          units: 3,
          grade: 16.5,
          status: 'passed',
          term_id: '4002',
        },
        {
          id: '4002-eng',
          code: '400205',
          name: 'زبان انگلیسی عمومی',
          units: 2,
          grade: 16.25,
          status: 'passed',
          term_id: '4002',
        },
        {
          id: '4002-pe2',
          code: '400206',
          name: 'تربیت بدنی 2',
          units: 1,
          grade: 17.5,
          status: 'passed',
          term_id: '4002',
        },
      ],
    },
    {
      id: '4011',
      term_code: '4011',
      term_name: 'نیمسال اول 1401-1402',
      term_gpa: 17.3,
      units_passed: 16,
      units_total: 17,
      courses: [
        {
          id: '4011-ds',
          code: '401101',
          name: 'ساختمان داده‌ها',
          units: 3,
          grade: 17.75,
          status: 'passed',
          term_id: '4011',
        },
        {
          id: '4011-alg',
          code: '401102',
          name: 'طراحی الگوریتم‌ها',
          units: 3,
          grade: 17.25,
          status: 'passed',
          term_id: '4011',
        },
        {
          id: '4011-arch',
          code: '401103',
          name: 'معماری کامپیوتر',
          units: 3,
          grade: 16.5,
          status: 'passed',
          term_id: '4011',
        },
        {
          id: '4011-logic',
          code: '401104',
          name: 'مدارهای منطقی',
          units: 3,
          grade: 17.0,
          status: 'passed',
          term_id: '4011',
        },
        {
          id: '4011-islamic',
          code: '401105',
          name: 'اندیشه اسلامی 1',
          units: 2,
          grade: 16.0,
          status: 'passed',
          term_id: '4011',
        },
        {
          id: '4011-persian',
          code: '401106',
          name: 'زبان فارسی تخصصی',
          units: 3,
          grade: 18.0,
          status: 'passed',
          term_id: '4011',
        },
      ],
    },
    {
      id: '4012',
      term_code: '4012',
      term_name: 'نیمسال دوم 1401-1402',
      term_gpa: 18.75,
      units_passed: 15,
      units_total: 15,
      courses: [
        {
          id: '4012-os',
          code: '401201',
          name: 'سیستم‌عامل',
          units: 3,
          grade: 18.5,
          status: 'passed',
          term_id: '4012',
        },
        {
          id: '4012-db',
          code: '401202',
          name: 'پایگاه داده‌ها',
          units: 3,
          grade: 18.75,
          status: 'passed',
          term_id: '4012',
        },
        {
          id: '4012-net',
          code: '401203',
          name: 'شبکه‌های کامپیوتری',
          units: 3,
          grade: 18.25,
          status: 'passed',
          term_id: '4012',
        },
        {
          id: '4012-se',
          code: '401204',
          name: 'مهندسی نرم‌افزار',
          units: 3,
          grade: 19.0,
          status: 'passed',
          term_id: '4012',
        },
        {
          id: '4012-islamic2',
          code: '401205',
          name: 'اندیشه اسلامی 2',
          units: 3,
          grade: 18.25,
          status: 'passed',
          term_id: '4012',
        },
      ],
    },
    {
      id: '4021',
      term_code: '4021',
      term_name: 'نیمسال اول 1402-1403',
      term_gpa: 17.85,
      units_passed: 14,
      units_total: 15,
      courses: [
        {
          id: '4021-ai',
          code: '402101',
          name: 'هوش مصنوعی',
          units: 3,
          grade: 18.0,
          status: 'passed',
          term_id: '4021',
        },
        {
          id: '4021-theory',
          code: '402102',
          name: 'نظریه زبان‌ها و ماشین‌ها',
          units: 3,
          grade: 17.5,
          status: 'passed',
          term_id: '4021',
        },
        {
          id: '4021-compiler',
          code: '402103',
          name: 'مبانی ترجمه و زبان‌های برنامه‌سازی',
          units: 3,
          grade: 17.75,
          status: 'passed',
          term_id: '4021',
        },
        {
          id: '4021-research',
          code: '402104',
          name: 'روش پژوهش و ارائه',
          units: 2,
          grade: 17.0,
          status: 'passed',
          term_id: '4021',
        },
        {
          id: '4021-pe3',
          code: '402105',
          name: 'ورزش 3',
          units: 1,
          grade: 18.0,
          status: 'passed',
          term_id: '4021',
        },
      ],
    },
  ],
};